name: nodeBuild

on:
  push:
    branches:
      - main # Change this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use Node.js version 16

      - name: Install npm modules
        run: npm install

      - name: Save artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules/

      - name: Save build output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: index.js
